apiVersion: v1
kind: Service
metadata:
  name: reina-deploy-svc
  labels:
    tier: front-end
    app: react
spec:
  type: LoadBalancer
  selector:
    app: react
  ports:
    - name: http
      port: 80
      targetPort: 3000
    